<a href="https://colab.research.google.com/github/saransh437/Feature_engineering/blob/main/feature_eng_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler , LabelEncoder , OrdinalEncoder

In [ ]:
# Raw Data
#    ↓
# Understand Problem -> Understand the Problem & Data <> Business goal? <> target column
#    ↓
# EDA -> Understand data behavior. <> missing values <> Outliers
#    ↓
# Cleaning -> handle missing value , duplicate , incorrect values, handle outliers , split data
#    ↓
# Transformations -> scaling , normalization , encoding categorical data
#    ↓
# Feature Creation -> Create new useful features from existing data
#    ↓
# Feature Selection -> Remove useless or harmful features. , Reduce overfitting ,Better generalization
#    ↓
# Scaling -> Make features comparable. and Never use future information.
#    ↓
# Validation -> Check if features actually help.
#    ↓
# Pipeline -> automate processing
#    ↓
# Model Training

In [ ]:
# Split the data immediately after basic cleaning and BEFORE feature engineering that learns from data. which prevent data leakage
# problem -> Test data information leaks into training. model will give high accuracy

In [ ]:
# machine learning ->
# data(50) ---> x(input data), y(target data)
# x---> x_train , x_test
# y ---> y_train , y_test
# for machine learning training we pass x_train and y_train then it learn and recognise pattern from it
# for ml testing -> (x_test) ---> y_pred

In [ ]:
# feature_engineering : process of using domain knowledge to extract features from raw data.
#  and these feature can be improve the performance of machine learning algorithm

In [ ]:
# 1. feature transformation : transforming one feature into another from so that it can perform better while training
# missing value imputation
# outlier detection
# feature scaling
# hndling categorical data

# 2. feature construction : manually created from the existing feature
# 3. feature selecttion: Remove useless or harmful features. , Reduce overfitting ,Better generalization
# 4. feature extraction: extracting from the existing feature programmatically.

In [ ]:
# 1. feature scaling: technique to standardize the independent features present in the data in a fixed range
# problem: age: 18-20 salary:300000-4000000
# Numbers have very different magnitudes.
# large numbers dominate learning and bias can be caused due to this(Algorithmic Bias)
# --------->1. standardization:Standardization (Z-score scaling) is a technique used to transform your data so that:
# Mean (μ) = 0
# Standard Deviation (σ) = 1
# value - mean/std
# when to use:
# Features have different scales
# When data is not in a fixed range
# k-mean , KNN ,PCA, gradient descent , Artificial neural network
# **** has no effect on outliers
#---------->2. Normalization(MinMaxScaler): Rescales values into a fixed range, usually 0 to 1 without disorting differences in the range of values
#              Basicly retain the data format.
              # properties : after scaling max value : 1 and min value :0
             # Use when:
             # when we already know the minimun and maximum in the given data.
             # Data has known boundaries
             # No extreme outliers
             # Distance-based algorithms
# very sensitive to the outlier if the data set have more outlier values will compress more
            #  Robust Scaling: Uses median and IQR (Interquartile Range) instead of mean & std.
            # use when :Dataset contains many outliers

STANDARDIZATION IMPLEMENTATION

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/covid_toy - covid_toy.csv')

In [ ]:
df.isnull().sum()  # handle null values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.drop(columns= ['city'])
df['gender'] = df['gender'].map({'Female':1,'Male':0 })
df['cough'] = df['cough'].map({'Mild':0,'Strong':1 })

In [ ]:
x = df.drop(columns = ['has_covid']) ### Input_data or training data
y = df['has_covid'] ### output or testing data

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(
    x,y,test_size=0.2 , random_state= 42
)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit(x_train)
x_train_sc_new = sc.transform(x_train)
x_test_sc_new = sc.transform(x_test)
x_train_sc_df = pd.DataFrame(x_train_sc_new , columns = x_train.columns)

Train data → past (learning phase)
Test data → future (evaluation phase)
# New Section
Fit(learn statistics) on train so learning uses only past knowledge; transform(apply) test,train so evaluation simulates future predictions.
*** if i fit on test data then it can cause data leakage
# New Section
We scale X because feature magnitude affects model learning and optimization. We usually don’t scale y because it represents the prediction target and does not influence feature weighting and are independent of each other , except in some regression or deep learning cases where scaling improves optimization stability.

In [ ]:
np.round(x_train_sc_df.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean   -0.00   -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01
min    -1.56   -1.19  -1.56  -0.82
25%    -0.94   -1.19  -0.51  -0.82
50%    -0.04    0.84   0.01  -0.82
75%     0.91    0.84   0.53   1.22
max     1.69    0.84   1.57   1.22

In [ ]:
# ENCODING : Encoding in feature engineering means converting categorical (text)
          #  data into numerical form so that machine learning models can understand and use it.
# Why encoding is needed ?
# ---> ML models perform mathematical operations → need numbers
# ---> Encoding helps represent categories in a structured way

# 1. Nominal Data: categories with NO natural order
                  # eg: City → Delhi, Mumbai, Chennai
# 2.Ordinal Data: categories with a meaningful order or ranking
                  # eg: Small < Medium < Large

In [ ]:
# 1. Label Encoding: Each category gets a unique number and always used on Output column not on input data as it give value implicitly
# 2. Ordinal Encoding : Similar to label encoding but order is meaningful.

In [3]:
df = pd.read_csv('customer.csv')
df.head(2)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No

In [4]:
x = df[['review','education']]
y = df['purchased']

In [5]:
x.head(1)

    review education
0  Average    School

In [6]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(x)
x = oe.transform(x)

In [ ]:
x

In [8]:
le = LabelEncoder()
le.fit(y)
y = le.transform(y)

In [9]:
y

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])